/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppMenu {
    }
    interface AppRoot {
    }
    interface PageAbout {
    }
    interface PageAuth {
    }
    interface PageHome {
    }
    interface TabsDashboard {
    }
    interface TabsHome {
    }
    interface TabsRoot {
    }
}
declare global {
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {
    }
    var HTMLPageAboutElement: {
        prototype: HTMLPageAboutElement;
        new (): HTMLPageAboutElement;
    };
    interface HTMLPageAuthElement extends Components.PageAuth, HTMLStencilElement {
    }
    var HTMLPageAuthElement: {
        prototype: HTMLPageAuthElement;
        new (): HTMLPageAuthElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLTabsDashboardElement extends Components.TabsDashboard, HTMLStencilElement {
    }
    var HTMLTabsDashboardElement: {
        prototype: HTMLTabsDashboardElement;
        new (): HTMLTabsDashboardElement;
    };
    interface HTMLTabsHomeElement extends Components.TabsHome, HTMLStencilElement {
    }
    var HTMLTabsHomeElement: {
        prototype: HTMLTabsHomeElement;
        new (): HTMLTabsHomeElement;
    };
    interface HTMLTabsRootElement extends Components.TabsRoot, HTMLStencilElement {
    }
    var HTMLTabsRootElement: {
        prototype: HTMLTabsRootElement;
        new (): HTMLTabsRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-menu": HTMLAppMenuElement;
        "app-root": HTMLAppRootElement;
        "page-about": HTMLPageAboutElement;
        "page-auth": HTMLPageAuthElement;
        "page-home": HTMLPageHomeElement;
        "tabs-dashboard": HTMLTabsDashboardElement;
        "tabs-home": HTMLTabsHomeElement;
        "tabs-root": HTMLTabsRootElement;
    }
}
declare namespace LocalJSX {
    interface AppMenu {
    }
    interface AppRoot {
    }
    interface PageAbout {
    }
    interface PageAuth {
    }
    interface PageHome {
    }
    interface TabsDashboard {
    }
    interface TabsHome {
    }
    interface TabsRoot {
    }
    interface IntrinsicElements {
        "app-menu": AppMenu;
        "app-root": AppRoot;
        "page-about": PageAbout;
        "page-auth": PageAuth;
        "page-home": PageHome;
        "tabs-dashboard": TabsDashboard;
        "tabs-home": TabsHome;
        "tabs-root": TabsRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-about": LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
            "page-auth": LocalJSX.PageAuth & JSXBase.HTMLAttributes<HTMLPageAuthElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "tabs-dashboard": LocalJSX.TabsDashboard & JSXBase.HTMLAttributes<HTMLTabsDashboardElement>;
            "tabs-home": LocalJSX.TabsHome & JSXBase.HTMLAttributes<HTMLTabsHomeElement>;
            "tabs-root": LocalJSX.TabsRoot & JSXBase.HTMLAttributes<HTMLTabsRootElement>;
        }
    }
}
